import { sql } from "drizzle-orm";
import { db } from "@/db";

/**
 * Zero-config safety net: creates the tables the first time the app talks to
 * the database, so a brand-new database works without running any SQL.
 *
 * The promise is memoized, so the DDL runs at most ONCE per process, not once
 * per request — every later call awaits the same settled promise. On failure
 * `ready` is reset so the next request retries.
 *
 * ⚠️ SOURCE OF TRUTH: `src/db/schema.ts` is authoritative. The DDL below is a
 * hand-maintained mirror and can drift from it. Real migrations now live in
 * `./drizzle` (generated by `npm run db:generate`), and the preferred deploy
 * path is `npm run db:migrate`. A unit test (`bootstrap.drift.test.ts`)
 * compares the columns declared here against `schema.ts` to catch drift.
 *
 * Set `SKIP_DB_BOOTSTRAP=1` in environments where migrations are applied as a
 * deploy step and the app's role should not have DDL privileges.
 */
let ready: Promise<void> | null = null;

export function ensureSchema(): Promise<void> {
  if (process.env.SKIP_DB_BOOTSTRAP === "1") return Promise.resolve();
  if (!ready) {
    ready = (async () => {
      await db.execute(sql`
        CREATE TABLE IF NOT EXISTS writing_samples (
          id SERIAL PRIMARY KEY,
          public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
          title VARCHAR(200) NOT NULL DEFAULT 'Untitled sample',
          content TEXT NOT NULL,
          word_count INTEGER NOT NULL DEFAULT 0,
          source VARCHAR(50) NOT NULL DEFAULT 'paste',
          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
      `);
      await db.execute(sql`
        CREATE TABLE IF NOT EXISTS style_profiles (
          id SERIAL PRIMARY KEY,
          name VARCHAR(120) NOT NULL DEFAULT 'My writing style',
          profile JSONB NOT NULL,
          summary TEXT NOT NULL DEFAULT '',
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
      `);
      await db.execute(sql`
        CREATE TABLE IF NOT EXISTS rewrite_jobs (
          id SERIAL PRIMARY KEY,
          original_text TEXT NOT NULL,
          rewritten_text TEXT NOT NULL,
          notes TEXT NOT NULL DEFAULT '',
          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
      `);
      await db.execute(sql`
        CREATE TABLE IF NOT EXISTS ai_scans (
          id SERIAL PRIMARY KEY,
          public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
          file_name VARCHAR(255) NOT NULL DEFAULT 'Pasted text',
          word_count INTEGER NOT NULL DEFAULT 0,
          score INTEGER NOT NULL,
          verdict VARCHAR(60) NOT NULL,
          signals JSONB NOT NULL,
          style_match JSONB,
          ai_opinion JSONB,
          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
      `);
      await db.execute(sql`
        ALTER TABLE ai_scans
        ADD COLUMN IF NOT EXISTS ai_opinion JSONB
      `);

      /**
       * Upgrade path for databases created before public_id existed.
       * CREATE TABLE IF NOT EXISTS is a no-op on an existing table, so the
       * column has to be added explicitly. Added nullable first, backfilled,
       * then constrained — adding it NOT NULL in one step fails on non-empty
       * tables. gen_random_uuid() is built into Postgres 13+.
       */
      for (const table of ["writing_samples", "ai_scans"] as const) {
        await db.execute(
          sql`ALTER TABLE ${sql.identifier(table)}
              ADD COLUMN IF NOT EXISTS public_id UUID DEFAULT gen_random_uuid()`,
        );
        await db.execute(
          sql`UPDATE ${sql.identifier(table)}
              SET public_id = gen_random_uuid() WHERE public_id IS NULL`,
        );
        await db.execute(
          sql`ALTER TABLE ${sql.identifier(table)}
              ALTER COLUMN public_id SET NOT NULL`,
        );
        await db.execute(
          sql`CREATE UNIQUE INDEX IF NOT EXISTS ${sql.identifier(
            `${table}_public_id_key`,
          )} ON ${sql.identifier(table)} (public_id)`,
        );
      }
    })().catch((err) => {
      ready = null; // allow retry on the next request
      console.error("ensureSchema failed", err);
      throw err;
    });
  }
  return ready;
}
