import { sql } from "drizzle-orm";
import { db } from "@/db";

/**
 * Zero-config safety net: creates the tables the first time the app talks to
 * the database, so a brand-new database works without running any SQL.
 *
 * The promise is memoized, so the DDL runs at most ONCE per process, not once
 * per request — every later call awaits the same settled promise. On failure
 * `ready` is reset so the next request retries.
 *
 * ⚠️ SOURCE OF TRUTH: `src/db/schema.ts` is authoritative. The DDL below is a
 * hand-maintained mirror and can drift from it. Real migrations now live in
 * `./drizzle` (generated by `npm run db:generate`), and the preferred deploy
 * path is `npm run db:migrate`. A unit test (`bootstrap.drift.test.ts`)
 * compares the columns declared here against `schema.ts` to catch drift.
 *
 * Set `SKIP_DB_BOOTSTRAP=1` in environments where migrations are applied as a
 * deploy step and the app's role should not have DDL privileges.
 */
let ready: Promise<void> | null = null;

export function ensureSchema(): Promise<void> {
  if (process.env.SKIP_DB_BOOTSTRAP === "1") return Promise.resolve();
  if (!ready) {
    ready = (async () => {
      await db.execute(sql`
        CREATE TABLE IF NOT EXISTS writing_samples (
          id SERIAL PRIMARY KEY,
          public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
          title VARCHAR(200) NOT NULL DEFAULT 'Untitled sample',
          content TEXT NOT NULL,
          word_count INTEGER NOT NULL DEFAULT 0,
          source VARCHAR(50) NOT NULL DEFAULT 'paste',
          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
      `);
      await db.execute(sql`
        CREATE TABLE IF NOT EXISTS style_profiles (
          id SERIAL PRIMARY KEY,
          name VARCHAR(120) NOT NULL DEFAULT 'My writing style',
          profile JSONB NOT NULL,
          summary TEXT NOT NULL DEFAULT '',
          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
      `);
      await db.execute(sql`
        CREATE TABLE IF NOT EXISTS rewrite_jobs (
          id SERIAL PRIMARY KEY,
          original_text TEXT NOT NULL,
          rewritten_text TEXT NOT NULL,
          notes TEXT NOT NULL DEFAULT '',
          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
      `);
      await db.execute(sql`
        CREATE TABLE IF NOT EXISTS ai_scans (
          id SERIAL PRIMARY KEY,
          public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
          file_name VARCHAR(255) NOT NULL DEFAULT 'Pasted text',
          word_count INTEGER NOT NULL DEFAULT 0,
          score INTEGER NOT NULL,
          verdict VARCHAR(60) NOT NULL,
          signals JSONB NOT NULL,
          style_match JSONB,
          ai_opinion JSONB,
          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
      `);
      await db.execute(sql`
        ALTER TABLE ai_scans
        ADD COLUMN IF NOT EXISTS ai_opinion JSONB
      `);
      await db.execute(sql`
        CREATE TABLE IF NOT EXISTS grammar_checks (
          id SERIAL PRIMARY KEY,
          public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
          file_name VARCHAR(255) NOT NULL DEFAULT 'Pasted text',
          word_count INTEGER NOT NULL DEFAULT 0,
          score INTEGER NOT NULL,
          verdict VARCHAR(60) NOT NULL,
          error_count INTEGER NOT NULL DEFAULT 0,
          warning_count INTEGER NOT NULL DEFAULT 0,
          suggestion_count INTEGER NOT NULL DEFAULT 0,
          source VARCHAR(20) NOT NULL DEFAULT 'paste',
          issues JSONB NOT NULL,
          stats JSONB NOT NULL,
          llm_model VARCHAR(80),
          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
      `);

      /**
       * Upgrade path for databases created before public_id existed.
       * CREATE TABLE IF NOT EXISTS is a no-op on an existing table, so the
       * column has to be added explicitly. Added nullable first, backfilled,
       * then constrained — adding it NOT NULL in one step fails on non-empty
       * tables. gen_random_uuid() is built into Postgres 13+.
       */
      for (const table of ["writing_samples", "ai_scans"] as const) {
        await db.execute(
          sql`ALTER TABLE ${sql.identifier(table)}
              ADD COLUMN IF NOT EXISTS public_id UUID DEFAULT gen_random_uuid()`,
        );
        await db.execute(
          sql`UPDATE ${sql.identifier(table)}
              SET public_id = gen_random_uuid() WHERE public_id IS NULL`,
        );
        await db.execute(
          sql`ALTER TABLE ${sql.identifier(table)}
              ALTER COLUMN public_id SET NOT NULL`,
        );
        /**
         * Guard on the SHAPE of the index, not its name. `IF NOT EXISTS` only
         * matches the literal name, and the two supported provisioning paths
         * name this differently: drizzle's migrations create
         * `<table>_public_id_unique`, while the inline UNIQUE above gets
         * Postgres's default `<table>_public_id_key`. Keying off the name
         * meant a drizzle-migrated database got a SECOND, redundant unique
         * index on the same column — double the write cost, forever.
         *
         * Done as a SELECT + conditional CREATE rather than a DO block: a DO
         * body is one string literal, so it cannot take bind parameters.
         */
        const existing = await db.execute<{
          index_name: string;
          constraint_backed: boolean;
        }>(
          sql`SELECT ic.relname AS index_name,
                     (con.oid IS NOT NULL) AS constraint_backed
              FROM pg_index i
              JOIN pg_class t ON t.oid = i.indrelid
              JOIN pg_class ic ON ic.oid = i.indexrelid
              JOIN pg_attribute a
                ON a.attrelid = t.oid
               AND a.attnum = i.indkey[0]
              LEFT JOIN pg_constraint con ON con.conindid = i.indexrelid
              WHERE t.relname = ${table}
                AND t.relnamespace = 'public'::regnamespace
                AND i.indisunique
                AND NOT i.indisprimary
                AND i.indnatts = 1
                AND a.attname = 'public_id'
              ORDER BY constraint_backed DESC, ic.relname`,
        );

        if (existing.rows.length === 0) {
          await db.execute(
            sql`CREATE UNIQUE INDEX IF NOT EXISTS ${sql.identifier(
              `${table}_public_id_key`,
            )} ON ${sql.identifier(table)} (public_id)`,
          );
        } else if (existing.rows.length > 1) {
          /**
           * One-time cleanup for databases provisioned before the guard above
           * checked index SHAPE instead of index NAME. Those databases were
           * migrated by drizzle (creating `<table>_public_id_unique`) and then
           * booted by the old bootstrap, whose
           * `CREATE UNIQUE INDEX IF NOT EXISTS <table>_public_id_key` could not
           * see the differently-named index and built a second one. Two
           * identical unique indexes on one column means every insert maintains
           * both, forever.
           *
           * Keep the constraint-backed index and drop the plain duplicates:
           * DROP INDEX refuses to touch an index owned by a constraint
           * ("cannot drop index ... because constraint ... requires it"), so
           * dropping the plain one is both the safe and the only direct option.
           * The ORDER BY puts constraint-backed first, so slice(1) is always
           * the droppable remainder. Uniqueness is never lost: the survivor is
           * enforcing it throughout.
           */
          const keep = existing.rows[0];
          for (const dupe of existing.rows.slice(1)) {
            if (dupe.constraint_backed) continue; // never orphan a constraint
            await db.execute(
              sql`DROP INDEX IF EXISTS ${sql.identifier(dupe.index_name)}`,
            );
            console.info(
              `ensureSchema: dropped redundant unique index ${dupe.index_name} ` +
                `on ${table} (kept ${keep.index_name})`,
            );
          }
        }
      }
    })().catch((err) => {
      ready = null; // allow retry on the next request
      console.error("ensureSchema failed", err);
      throw err;
    });
  }
  return ready;
}
